name: Deploy VPC Service Controls with Terraform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

env:
  PROJECT_ID: unity-ai-ci-cd-pipeline-poc
  TF_STATE_BUCKET: vpc-sc-terraform-state-unity-ai

jobs:
  terraform-deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up gcloud CLI
      run: |
        echo "Setting up gcloud CLI"
        gcloud config set project ${{ env.PROJECT_ID }}
      
    - name: Authenticate with Google Cloud
      run: |
        # Verify authentication
        gcloud auth list
    
    # - name: Create Terraform state bucket if not exists
      #run: |
       # if ! gsutil ls -b gs://${{ env.TF_STATE_BUCKET }} 2>/dev/null; then
        #  echo "Creating Terraform state bucket..."
         # gsutil mb -l us-central1 gs://${{ env.TF_STATE_BUCKET }}
          #gsutil versioning set on gs://${{ env.TF_STATE_BUCKET }}
        #else
         # echo "Terraform state bucket already exists."
        #fi

    - name: Terraform Init
      run: |
        pwd
        cd .github/workflows/terraform
        terraform init
    
    - name: Terraform Plan
      run: |
        cd .github/workflows/terraform
        terraform plan -out=tfplan
    
    - name: Terraform Apply
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        cd .github/workflows/terraform
        terraform apply -auto-approve tfplan
